### ISSUE TITLE
Determine if Put was create or update

### ISSUE THREAD

**Issue by subprotocol** [oracle/nosql-java-sdk#115]
Currently getExistingVersion() is always empty unless you:
1. Specify setReturnRow(true)
2. Specify one of these options: IfAbsent, IfPresent, IfVersion.
3. The condition fails

My issue is that I need the put operation to succeed **and** return getExistingVersion() for the previous version—if one exists—**without** specifying a conditional Option.

Using the older NoSQL api this was possible by setting ReturnRow.Choice.VERSION.

**Comment by gmfeinberg** [comment]
We will look at enhancing the semantics of the existing calls to support this. There is an internal ticket for this

**Comment by subprotocol** [comment]
Thank you!
