### ISSUE TITLE
Instruction for running 'Quickstart' for cloud simulator has a typo

### ISSUE THREAD

**Issue by javierdiegof** [oracle/nosql-java-sdk#3]
Hi, hope you're doing fine. 

Just a very minor typo. The instructions to run the 'Quickstart' for the cloud simulator specify running as an argument `cloudsi` instead of `cloudsim`.
```
$ java -cp .:<path-to-nosqldriver.jar> Quickstart -service cloudsi -endpoint http://localhost:8080
```

**Comment by gmfeinberg** [comment]
Thanks for the heads up. Fixed!
