### ISSUE TITLE
[Documentation] Version 5.4.14 is not available at the maven central

### ISSUE THREAD

**Issue by otaviojava** [oracle/nosql-java-sdk#99]
When I checked the [readme](https://github.com/oracle/nosql-java-sdk/blob/main/README.md) file, it explained version 5.4.14.

However, the version available is until 5.4.13:

Reference:

- https://central.sonatype.com/artifact/com.oracle.nosql.sdk/nosqldriver/5.4.13/versions

**Comment by gmfeinberg** [comment]
Thanks for the comment. The 5.4.14 version is in the process of being staged/released at maven central. It should be a few days

**Comment by gmfeinberg** [comment]
5.4.14 has been made available on maven central
